/**
 * Integration Test for Transitive Dead URL Detection
 * Task 6: Test transitive dead URLs
 * 
 * This test validates the complete transitive dead URL detection flow including:
 * - Lockfile parsing (npm, yarn, pnpm)
 * - Dead URL detection in transitive dependencies
 * - Parent chain identification
 * - Report section generation
 * - Lockfile regeneration
 * 
 * Requirements: 1.1-1.5, 4.1-4.3, 5.1-5.2
 */

import * as assert from 'assert';
import { describe, it, beforeEach, afterEach } from 'node:test';
import * as fs from 'fs/promises';
import * as path from 'path';
import * as os from 'os';
import { DeadUrlHandler } from '../services/deadUrlHandler';
import { LockfileParser } from '../services/lockfileParser';
import { URLValidator } from '../services/urlValidator';
import { PackageReplacementRegistry } from '../services/packageReplacementRegistry';

describe('Transitive Dead URL Detection Integration Tests', () => {
  let testRepoPath: string;
  let deadUrlHandler: DeadUrlHandler;
  let lockfileParser: LockfileParser;

  beforeEach(async () => {
    // Create a temporary test repository
    testRepoPath = await fs.mkdtemp(path.join(os.tmpdir(), 'codecrypt-test-'));
    
    // Initialize services
    lockfileParser = new LockfileParser();
    const urlValidator = new URLValidator();
    const registry = new PackageReplacementRegistry();
    deadUrlHandler = new DeadUrlHandler(urlValidator, lockfileParser, registry);
  });

  afterEach(async () => {
    // Clean up test repository
    try {
      await fs.rm(testRepoPath, { recursive: true, force: true });
    } catch (error) {
      // Ignore cleanup errors
    }
  });

  /**
   * Test 1: npm lockfile parsing with transitive dead URLs
   * Requirements: 1.1, 1.2, 4.1
   */
  it('should parse npm lockfile and detect transitive dead URLs', async () => {
    // Create package.json with direct dependencies
    const packageJson = {
      name: 'test-repo',
      version: '1.0.0',
      dependencies: {
        'express': '^4.17.1'
      }
    };
    await fs.writeFile(
      path.join(testRepoPath, 'package.json'),
      JSON.stringify(packageJson, null, 2)
    );

    // Create package-lock.json with transitive dead URL
    const packageLock = {
      name: 'test-repo',
      version: '1.0.0',
      lockfileVersion: 2,
      requires: true,
      packages: {
        '': {
          name: 'test-repo',
          version: '1.0.0',
          dependencies: {
            'express': '^4.17.1'
          }
        },
        'node_modules/express': {
          version: '4.17.1',
          resolved: 'https://registry.npmjs.org/express/-/express-4.17.1.tgz',
          integrity: 'sha512-...',
          dependencies: {
            'querystring': 'https://github.com/substack/querystring/archive/0.2.0-ie8.tar.gz'
          }
        },
        'node_modules/querystring': {
          version: '0.2.0',
          resolved: 'https://github.com/substack/querystring/archive/0.2.0-ie8.tar.gz',
          integrity: 'sha512-...'
        }
      }
    };
    await fs.writeFile(
      path.join(testRepoPath, 'package-lock.json'),
      JSON.stringify(packageLock, null, 2)
    );

    // Parse lockfile
    const transitiveDeps = await lockfileParser.parseLockfile(testRepoPath);

    // Verify transitive dependency was found
    assert.ok(transitiveDeps.length > 0, 'Should find transitive dependencies');
    
    const querystringDep = transitiveDeps.find(dep => dep.name === 'querystring');
    assert.ok(querystringDep, 'Should find querystring transitive dependency');
    assert.strictEqual(
      querystringDep.resolvedUrl,
      'https://github.com/substack/querystring/archive/0.2.0-ie8.tar.gz',
      'Should extract correct URL'
    );
    assert.ok(querystringDep.depth > 0, 'Should have depth > 0 for transitive dependency');
  });

  /**
   * Test 2: yarn lockfile parsing with transitive dead URLs
   * Requirements: 1.1, 4.1
   */
  it('should parse yarn lockfile and detect transitive dead URLs', async () => {
    // Create package.json
    const packageJson = {
      name: 'test-repo',
      version: '1.0.0',
      dependencies: {
        'express': '^4.17.1'
      }
    };
    await fs.writeFile(
      path.join(testRepoPath, 'package.json'),
      JSON.stringify(packageJson, null, 2)
    );

    // Create yarn.lock with transitive dead URL
    const yarnLock = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

express@^4.17.1:
  version "4.17.1"
  resolved "https://registry.yarnpkg.com/express/-/express-4.17.1.tgz"
  integrity sha512-...
  dependencies:
    querystring "https://github.com/substack/querystring/archive/0.2.0-ie8.tar.gz"

querystring@https://github.com/substack/querystring/archive/0.2.0-ie8.tar.gz:
  version "0.2.0"
  resolved "https://github.com/substack/querystring/archive/0.2.0-ie8.tar.gz#abc123"
  integrity sha512-...
`;
    await fs.writeFile(path.join(testRepoPath, 'yarn.lock'), yarnLock);

    // Parse lockfile
    const transitiveDeps = await lockfileParser.parseLockfile(testRepoPath);

    // Verify transitive dependency was found
    assert.ok(transitiveDeps.length > 0, 'Should find transitive dependencies');
    
    const querystringDep = transitiveDeps.find(dep => dep.name === 'querystring');
    assert.ok(querystringDep, 'Should find querystring transitive dependency');
    assert.ok(
      querystringDep.resolvedUrl.includes('github.com/substack/querystring'),
      'Should extract correct URL'
    );
  });

  /**
   * Test 3: pnpm lockfile parsing with transitive dead URLs
   * Requirements: 1.1, 4.1
   */
  it('should parse pnpm lockfile and detect transitive dead URLs', async () => {
    // Create package.json
    const packageJson = {
      name: 'test-repo',
      version: '1.0.0',
      dependencies: {
        'express': '^4.17.1'
      }
    };
    await fs.writeFile(
      path.join(testRepoPath, 'package.json'),
      JSON.stringify(packageJson, null, 2)
    );

    // Create pnpm-lock.yaml with transitive dead URL
    const pnpmLock = `lockfileVersion: 5.4

specifiers:
  express: ^4.17.1

dependencies:
  express: 4.17.1

packages:

  /express/4.17.1:
    resolution: {integrity: sha512-...}
    dependencies:
      querystring: 0.2.0
    dev: false

  /querystring/0.2.0:
    resolution: {tarball: https://github.com/substack/querystring/archive/0.2.0-ie8.tar.gz}
    dev: false
`;
    await fs.writeFile(path.join(testRepoPath, 'pnpm-lock.yaml'), pnpmLock);

    // Parse lockfile
    const transitiveDeps = await lockfileParser.parseLockfile(testRepoPath);

    // Verify transitive dependency was found
    assert.ok(transitiveDeps.length > 0, 'Should find transitive dependencies');
    
    const querystringDep = transitiveDeps.find(dep => dep.name === 'querystring');
    assert.ok(querystringDep, 'Should find querystring transitive dependency');
    assert.ok(
      querystringDep.resolvedUrl.includes('github.com/substack/querystring'),
      'Should extract correct URL'
    );
  });

  /**
   * Test 4: Dead URL detection with parent chain
   * Requirements: 1.2, 1.3, 5.2
   */
  it('should detect dead URLs and identify parent chains', async () => {
    // Create package.json
    const packageJson = {
      name: 'test-repo',
      version: '1.0.0',
      dependencies: {
        'express': '^4.17.1'
      }
    };
    await fs.writeFile(
      path.join(testRepoPath, 'package.json'),
      JSON.stringify(packageJson, null, 2)
    );

    // Create package-lock.json with transitive dead URL
    const packageLock = {
      name: 'test-repo',
      version: '1.0.0',
      lockfileVersion: 2,
      requires: true,
      packages: {
        '': {
          name: 'test-repo',
          version: '1.0.0',
          dependencies: {
            'express': '^4.17.1'
          }
        },
        'node_modules/express': {
          version: '4.17.1',
          resolved: 'https://registry.npmjs.org/express/-/express-4.17.1.tgz',
          integrity: 'sha512-...'
        },
        'node_modules/querystring': {
          version: '0.2.0',
          resolved: 'https://github.com/substack/querystring/archive/0.2.0-ie8.tar.gz',
          integrity: 'sha512-...'
        }
      }
    };
    await fs.writeFile(
      path.join(testRepoPath, 'package-lock.json'),
      JSON.stringify(packageLock, null, 2)
    );

    // Handle dead URLs with transitive analysis
    const directDeps = new Map<string, string>([
      ['express', '^4.17.1']
    ]);

    const summary = await deadUrlHandler.handleDeadUrlsWithTransitive(
      testRepoPath,
      directDeps
    );

    // Verify dead URL was detected
    assert.ok(summary.totalChecked > 0, 'Should check dependencies');
    
    // Find querystring result
    const querystringResult = summary.results.find(r => r.packageName === 'querystring');
    
    if (querystringResult) {
      // Verify it was detected as a dead URL or replaced via registry
      assert.ok(
        querystringResult.isUrlDead || querystringResult.action === 'replaced',
        'Should detect dead URL or apply registry replacement'
      );
      
      // Verify depth is set for transitive dependency
      assert.ok(
        querystringResult.depth !== undefined,
        'Should have depth for transitive dependency'
      );
      
      // If resolved, verify npm alternative was found
      if (querystringResult.resolved) {
        assert.ok(
          querystringResult.npmAlternative,
          'Should find npm alternative'
        );
      }
    }
  });

  /**
   * Test 5: Report generation with dead URL section
   * Requirements: 5.1, 5.3, 5.4
   */
  it('should generate report with dead URL resolution section', async () => {
    // Create package.json
    const packageJson = {
      name: 'test-repo',
      version: '1.0.0',
      dependencies: {
        'express': '^4.17.1'
      }
    };
    await fs.writeFile(
      path.join(testRepoPath, 'package.json'),
      JSON.stringify(packageJson, null, 2)
    );

    // Create package-lock.json with transitive dead URL
    const packageLock = {
      name: 'test-repo',
      version: '1.0.0',
      lockfileVersion: 2,
      requires: true,
      packages: {
        '': {
          name: 'test-repo',
          version: '1.0.0',
          dependencies: {
            'express': '^4.17.1'
          }
        },
        'node_modules/querystring': {
          version: '0.2.0',
          resolved: 'https://github.com/substack/querystring/archive/0.2.0-ie8.tar.gz',
          integrity: 'sha512-...'
        }
      }
    };
    await fs.writeFile(
      path.join(testRepoPath, 'package-lock.json'),
      JSON.stringify(packageLock, null, 2)
    );

    // Handle dead URLs
    const directDeps = new Map<string, string>([
      ['express', '^4.17.1']
    ]);

    const summary = await deadUrlHandler.handleDeadUrlsWithTransitive(
      testRepoPath,
      directDeps
    );

    // Generate report
    const report = deadUrlHandler.generateReport(summary);

    // Verify report structure
    assert.ok(report, 'Should generate report');
    assert.ok(report.includes('Dead URL Handling Report'), 'Should have report title');
    assert.ok(report.includes('Total URL-based dependencies checked'), 'Should have summary');
    
    // Verify report includes details
    if (summary.results.length > 0) {
      assert.ok(report.includes('Details:'), 'Should have details section');
    }
    
    // Verify grouping by status
    const hasResolved = summary.results.some(r => r.action === 'replaced');
    const hasRemoved = summary.results.some(r => r.action === 'removed');
    
    if (hasResolved) {
      assert.ok(report.includes('→'), 'Should show replaced dependencies');
    }
    
    if (hasRemoved) {
      assert.ok(report.includes('✗'), 'Should show removed dependencies');
    }
  });

  /**
   * Test 6: Lockfile deletion and regeneration
   * Requirements: 4.1, 4.2, 4.3
   */
  it('should delete lockfiles in preparation for regeneration', async () => {
    // Create multiple lockfiles
    await fs.writeFile(path.join(testRepoPath, 'package-lock.json'), '{}');
    await fs.writeFile(path.join(testRepoPath, 'yarn.lock'), '');
    await fs.writeFile(path.join(testRepoPath, 'pnpm-lock.yaml'), '');

    // Verify files exist
    await fs.access(path.join(testRepoPath, 'package-lock.json'));
    await fs.access(path.join(testRepoPath, 'yarn.lock'));
    await fs.access(path.join(testRepoPath, 'pnpm-lock.yaml'));

    // Delete lockfiles
    await lockfileParser.deleteLockfiles(testRepoPath);

    // Verify files are deleted
    let filesDeleted = 0;
    
    try {
      await fs.access(path.join(testRepoPath, 'package-lock.json'));
    } catch {
      filesDeleted++;
    }
    
    try {
      await fs.access(path.join(testRepoPath, 'yarn.lock'));
    } catch {
      filesDeleted++;
    }
    
    try {
      await fs.access(path.join(testRepoPath, 'pnpm-lock.yaml'));
    } catch {
      filesDeleted++;
    }

    assert.strictEqual(filesDeleted, 3, 'Should delete all lockfiles');
  });

  /**
   * Test 7: Multiple transitive dead URLs at different depths
   * Requirements: 1.5
   */
  it('should handle multiple transitive dead URLs at different depths', async () => {
    // Create package.json
    const packageJson = {
      name: 'test-repo',
      version: '1.0.0',
      dependencies: {
        'express': '^4.17.1'
      }
    };
    await fs.writeFile(
      path.join(testRepoPath, 'package.json'),
      JSON.stringify(packageJson, null, 2)
    );

    // Create package-lock.json with multiple transitive dead URLs at different depths
    const packageLock = {
      name: 'test-repo',
      version: '1.0.0',
      lockfileVersion: 2,
      requires: true,
      packages: {
        '': {
          name: 'test-repo',
          version: '1.0.0',
          dependencies: {
            'express': '^4.17.1'
          }
        },
        'node_modules/express': {
          version: '4.17.1',
          resolved: 'https://registry.npmjs.org/express/-/express-4.17.1.tgz',
          integrity: 'sha512-...'
        },
        'node_modules/querystring': {
          version: '0.2.0',
          resolved: 'https://github.com/substack/querystring/archive/0.2.0-ie8.tar.gz',
          integrity: 'sha512-...'
        },
        'node_modules/express/node_modules/old-package': {
          version: '1.0.0',
          resolved: 'https://github.com/old-org/old-package/archive/v1.0.0.tar.gz',
          integrity: 'sha512-...'
        }
      }
    };
    await fs.writeFile(
      path.join(testRepoPath, 'package-lock.json'),
      JSON.stringify(packageLock, null, 2)
    );

    // Parse lockfile
    const transitiveDeps = await lockfileParser.parseLockfile(testRepoPath);

    // Verify multiple dependencies found
    assert.ok(transitiveDeps.length >= 2, 'Should find multiple transitive dependencies');
    
    // Verify different depths
    const depths = transitiveDeps.map(dep => dep.depth);
    const uniqueDepths = new Set(depths);
    
    // Should have dependencies at different depths
    assert.ok(uniqueDepths.size > 0, 'Should have dependencies at various depths');
    
    // Verify sorting by depth (deepest first)
    const sortedDeps = [...transitiveDeps].sort((a, b) => b.depth - a.depth);
    assert.deepStrictEqual(
      sortedDeps.map(d => d.name),
      transitiveDeps.map(d => d.name),
      'Dependencies should be sorted by depth (deepest first)'
    );
  });

  /**
   * Test 8: Registry pattern matching for known dead URLs
   * Requirements: 3.1, 3.2, 3.4
   */
  it('should apply registry pattern matching for known dead URLs', async () => {
    // Create package.json
    const packageJson = {
      name: 'test-repo',
      version: '1.0.0',
      dependencies: {
        'express': '^4.17.1'
      }
    };
    await fs.writeFile(
      path.join(testRepoPath, 'package.json'),
      JSON.stringify(packageJson, null, 2)
    );

    // Create package-lock.json with querystring dead URL (known in registry)
    const packageLock = {
      name: 'test-repo',
      version: '1.0.0',
      lockfileVersion: 2,
      requires: true,
      packages: {
        '': {
          name: 'test-repo',
          version: '1.0.0',
          dependencies: {
            'express': '^4.17.1'
          }
        },
        'node_modules/querystring': {
          version: '0.2.0',
          resolved: 'https://github.com/substack/querystring/archive/0.2.0-ie8.tar.gz',
          integrity: 'sha512-...'
        }
      }
    };
    await fs.writeFile(
      path.join(testRepoPath, 'package-lock.json'),
      JSON.stringify(packageLock, null, 2)
    );

    // Handle dead URLs
    const directDeps = new Map<string, string>([
      ['express', '^4.17.1']
    ]);

    const summary = await deadUrlHandler.handleDeadUrlsWithTransitive(
      testRepoPath,
      directDeps
    );

    // Find querystring result
    const querystringResult = summary.results.find(r => r.packageName === 'querystring');
    
    if (querystringResult) {
      // Should be resolved via registry pattern or npm lookup
      assert.ok(
        querystringResult.resolved || querystringResult.action === 'replaced',
        'Should resolve querystring via registry pattern or npm'
      );
      
      // Should have a warning explaining the resolution
      if (querystringResult.warning) {
        assert.ok(
          querystringResult.warning.includes('Registry') || 
          querystringResult.warning.includes('npm'),
          'Should explain resolution strategy'
        );
      }
    }
  });

  /**
   * Test 9: No lockfile scenario
   * Requirements: 1.1, 4.5
   */
  it('should handle repositories without lockfiles gracefully', async () => {
    // Create package.json only (no lockfile)
    const packageJson = {
      name: 'test-repo',
      version: '1.0.0',
      dependencies: {
        'express': '^4.17.1'
      }
    };
    await fs.writeFile(
      path.join(testRepoPath, 'package.json'),
      JSON.stringify(packageJson, null, 2)
    );

    // Detect lockfile type
    const lockfileType = await lockfileParser.detectLockfileType(testRepoPath);
    assert.strictEqual(lockfileType, null, 'Should detect no lockfile');

    // Parse lockfile (should return empty array)
    const transitiveDeps = await lockfileParser.parseLockfile(testRepoPath);
    assert.strictEqual(transitiveDeps.length, 0, 'Should return empty array for no lockfile');

    // Handle dead URLs (should only process direct dependencies)
    const directDeps = new Map<string, string>([
      ['express', '^4.17.1']
    ]);

    const summary = await deadUrlHandler.handleDeadUrlsWithTransitive(
      testRepoPath,
      directDeps
    );

    // Should complete without errors
    assert.ok(summary, 'Should handle no lockfile gracefully');
    assert.strictEqual(summary.totalChecked, 0, 'Should not check transitive deps without lockfile');
  });

  /**
   * Test 10: Comprehensive end-to-end scenario
   * Requirements: All (1.1-1.5, 4.1-4.3, 5.1-5.2)
   */
  it('should complete full transitive dead URL detection workflow', async () => {
    // Create package.json with direct dependencies
    const packageJson = {
      name: 'test-repo',
      version: '1.0.0',
      dependencies: {
        'express': '^4.17.1',
        'lodash': '^4.17.21'
      }
    };
    await fs.writeFile(
      path.join(testRepoPath, 'package.json'),
      JSON.stringify(packageJson, null, 2)
    );

    // Create package-lock.json with transitive dead URLs
    const packageLock = {
      name: 'test-repo',
      version: '1.0.0',
      lockfileVersion: 2,
      requires: true,
      packages: {
        '': {
          name: 'test-repo',
          version: '1.0.0',
          dependencies: {
            'express': '^4.17.1',
            'lodash': '^4.17.21'
          }
        },
        'node_modules/express': {
          version: '4.17.1',
          resolved: 'https://registry.npmjs.org/express/-/express-4.17.1.tgz',
          integrity: 'sha512-...'
        },
        'node_modules/lodash': {
          version: '4.17.21',
          resolved: 'https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz',
          integrity: 'sha512-...'
        },
        'node_modules/querystring': {
          version: '0.2.0',
          resolved: 'https://github.com/substack/querystring/archive/0.2.0-ie8.tar.gz',
          integrity: 'sha512-...'
        }
      }
    };
    await fs.writeFile(
      path.join(testRepoPath, 'package-lock.json'),
      JSON.stringify(packageLock, null, 2)
    );

    // Step 1: Detect lockfile type
    const lockfileType = await lockfileParser.detectLockfileType(testRepoPath);
    assert.strictEqual(lockfileType, 'npm', 'Should detect npm lockfile');

    // Step 2: Parse lockfile for transitive dependencies
    const transitiveDeps = await lockfileParser.parseLockfile(testRepoPath);
    assert.ok(transitiveDeps.length > 0, 'Should find transitive dependencies');

    // Step 3: Handle dead URLs with transitive analysis
    const directDeps = new Map<string, string>([
      ['express', '^4.17.1'],
      ['lodash', '^4.17.21']
    ]);

    const summary = await deadUrlHandler.handleDeadUrlsWithTransitive(
      testRepoPath,
      directDeps
    );

    // Step 4: Verify summary
    assert.ok(summary.totalChecked > 0, 'Should check dependencies');
    assert.ok(summary.results.length > 0, 'Should have results');

    // Step 5: Generate report
    const report = deadUrlHandler.generateReport(summary);
    assert.ok(report, 'Should generate report');
    assert.ok(report.includes('Dead URL Handling Report'), 'Should have report title');

    // Step 6: Verify report contains transitive dependency information
    const hasTransitiveInfo = summary.results.some(r => r.depth !== undefined && r.depth > 0);
    if (hasTransitiveInfo) {
      assert.ok(true, 'Report should include transitive dependency information');
    }

    // Step 7: Verify lockfile can be deleted (preparation for regeneration)
    await lockfileParser.deleteLockfiles(testRepoPath);
    
    try {
      await fs.access(path.join(testRepoPath, 'package-lock.json'));
      assert.fail('Lockfile should be deleted');
    } catch {
      assert.ok(true, 'Lockfile successfully deleted');
    }
  });
});

