/**
 * Integration Test: yarn Lockfile Parsing
 * 
 * Tests yarn lockfile (yarn.lock) parsing with URL-based dependencies.
 * Validates parsing, extraction, and regeneration functionality.
 * 
 * Requirements: 1.1, 4.1-4.2
 */

import * as assert from 'assert';
import { describe, it, beforeEach, afterEach } from 'node:test';
import * as fs from 'fs/promises';
import * as path from 'path';
import * as os from 'os';
import { createLockfileParser } from '../services/lockfileParser';
import { getLogger } from '../utils/logger';

const logger = getLogger();

describe('yarn Lockfile Parsing Integration Tests', () => {
  let testRepoPath: string;
  let lockfileParser: ReturnType<typeof createLockfileParser>;

  beforeEach(async () => {
    // Create temporary test directory
    testRepoPath = await fs.mkdtemp(path.join(os.tmpdir(), 'codecrypt-yarn-lockfile-test-'));
    lockfileParser = createLockfileParser();
    logger.info(`Created test repo at: ${testRepoPath}`);
  });

  afterEach(async () => {
    // Clean up test directory
    try {
      await fs.rm(testRepoPath, { recursive: true, force: true });
      logger.info(`Cleaned up test repo: ${testRepoPath}`);
    } catch (error) {
      logger.error('Failed to clean up test repo', error);
    }
  });

  /**
   * Test 1: Parse yarn lockfile with URL-based dependency
   * Validates: Requirements 1.1, 4.1
   */
  it('should parse yarn lockfile and extract URL-based dependencies', async () => {
    // Create package.json
    const packageJson = {
      name: 'test-repo',
      version: '1.0.0',
      dependencies: {
        'querystring': 'https://github.com/substack/querystring/archive/0.2.0-ie8.tar.gz'
      }
    };
    await fs.writeFile(
      path.join(testRepoPath, 'package.json'),
      JSON.stringify(packageJson, null, 2)
    );

    // Create yarn.lock with URL dependency
    const lockfileContent = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

querystring@https://github.com/substack/querystring/archive/0.2.0-ie8.tar.gz:
  version "0.2.0"
  resolved "https://github.com/substack/querystring/archive/0.2.0-ie8.tar.gz#abc123"
`;
    await fs.writeFile(
      path.join(testRepoPath, 'yarn.lock'),
      lockfileContent
    );

    // Detect lockfile type
    const lockfileType = await lockfileParser.detectLockfileType(testRepoPath);
    assert.strictEqual(lockfileType, 'yarn', 'Should detect yarn lockfile');

    // Parse lockfile
    const transitiveDeps = await lockfileParser.parseLockfile(testRepoPath);

    // Verify URL-based dependency was extracted
    assert.ok(transitiveDeps.length > 0, 'Should find at least one URL-based dependency');
    
    const querystringDep = transitiveDeps.find(dep => dep.name === 'querystring');
    assert.ok(querystringDep, 'Should find querystring dependency');
    assert.strictEqual(
      querystringDep.resolvedUrl,
      'https://github.com/substack/querystring/archive/0.2.0-ie8.tar.gz#abc123',
      'Should extract correct URL'
    );
    assert.ok(querystringDep.depth >= 0, 'Should have valid depth');

    logger.info('✓ yarn lockfile parsing successful');
  });

  /**
   * Test 2: Parse yarn lockfile with multiple URL-based dependencies
   * Validates: Requirements 1.1
   */
  it('should extract multiple URL-based dependencies from yarn lockfile', async () => {
    // Create yarn lockfile with multiple URL dependencies
    const lockfileContent = `# yarn lockfile v1

package-a@https://github.com/user/package-a/archive/v1.0.0.tar.gz:
  version "1.0.0"
  resolved "https://github.com/user/package-a/archive/v1.0.0.tar.gz"

package-b@https://github.com/user/package-b/archive/v2.0.0.tar.gz:
  version "2.0.0"
  resolved "https://github.com/user/package-b/archive/v2.0.0.tar.gz"

package-c@git+https://github.com/user/package-c.git#abc123:
  version "3.0.0"
  resolved "git+https://github.com/user/package-c.git#abc123"

normal-package@^1.0.0:
  version "1.0.0"
  resolved "https://registry.npmjs.org/normal-package/-/normal-package-1.0.0.tgz"
  integrity sha512-test123
`;
    await fs.writeFile(
      path.join(testRepoPath, 'yarn.lock'),
      lockfileContent
    );

    // Parse lockfile
    const transitiveDeps = await lockfileParser.parseLockfile(testRepoPath);

    // Verify all URL-based dependencies were extracted (but not npm registry ones)
    assert.strictEqual(transitiveDeps.length, 3, 'Should find exactly 3 URL-based dependencies');
    
    const packageNames = transitiveDeps.map(dep => dep.name).sort();
    assert.deepStrictEqual(
      packageNames,
      ['package-a', 'package-b', 'package-c'],
      'Should extract correct package names'
    );

    // Verify npm registry package was excluded
    const normalPackage = transitiveDeps.find(dep => dep.name === 'normal-package');
    assert.strictEqual(normalPackage, undefined, 'Should not include npm registry packages');

    logger.info('✓ Multiple URL-based dependencies extracted successfully');
  });

  /**
   * Test 3: Delete yarn lockfile
   * Validates: Requirements 4.1
   */
  it('should delete yarn lockfile when requested', async () => {
    // Create lockfile
    await fs.writeFile(
      path.join(testRepoPath, 'yarn.lock'),
      '# yarn lockfile v1\n'
    );

    // Verify lockfile exists
    await fs.access(path.join(testRepoPath, 'yarn.lock'));

    // Delete lockfiles
    await lockfileParser.deleteLockfiles(testRepoPath);

    // Verify lockfile was deleted
    try {
      await fs.access(path.join(testRepoPath, 'yarn.lock'));
      assert.fail('Lockfile should have been deleted');
    } catch (error: any) {
      assert.strictEqual(error.code, 'ENOENT', 'Lockfile should not exist');
    }

    logger.info('✓ Lockfile deletion successful');
  });

  /**
   * Test 4: Handle malformed yarn lockfile gracefully
   * Validates: Requirements 1.1
   */
  it('should handle malformed yarn lockfile gracefully', async () => {
    // Create malformed lockfile
    await fs.writeFile(
      path.join(testRepoPath, 'yarn.lock'),
      '# yarn lockfile v1\nthis is not valid yarn lock format {'
    );

    // Parse lockfile (should return empty array and not throw)
    const transitiveDeps = await lockfileParser.parseLockfile(testRepoPath);
    
    // The parser should handle this gracefully
    assert.ok(Array.isArray(transitiveDeps), 'Should return an array');

    logger.info('✓ Malformed lockfile handled gracefully');
  });

  /**
   * Test 5: Extract scoped package names correctly from yarn lockfile
   * Validates: Requirements 1.1
   */
  it('should extract scoped package names correctly from yarn lockfile', async () => {
    // Create lockfile with scoped packages
    const lockfileContent = `# yarn lockfile v1

"@babel/core@https://github.com/babel/babel/archive/v7.0.0.tar.gz":
  version "7.0.0"
  resolved "https://github.com/babel/babel/archive/v7.0.0.tar.gz"

"@types/node@https://github.com/DefinitelyTyped/DefinitelyTyped/archive/node-14.0.0.tar.gz":
  version "14.0.0"
  resolved "https://github.com/DefinitelyTyped/DefinitelyTyped/archive/node-14.0.0.tar.gz"
`;
    await fs.writeFile(
      path.join(testRepoPath, 'yarn.lock'),
      lockfileContent
    );

    // Parse lockfile
    const transitiveDeps = await lockfileParser.parseLockfile(testRepoPath);

    // Verify scoped packages were extracted correctly
    assert.strictEqual(transitiveDeps.length, 2, 'Should find 2 scoped packages');
    
    const babelDep = transitiveDeps.find(dep => dep.name === '@babel/core');
    const typesDep = transitiveDeps.find(dep => dep.name === '@types/node');
    
    assert.ok(babelDep, 'Should find @babel/core');
    assert.ok(typesDep, 'Should find @types/node');

    logger.info('✓ Scoped package names extracted correctly');
  });

  /**
   * Test 6: Filter out npm registry URLs from yarn lockfile
   * Validates: Requirements 1.1
   */
  it('should filter out npm registry URLs and only extract non-registry URLs', async () => {
    // Create lockfile with mix of registry and non-registry URLs
    const lockfileContent = `# yarn lockfile v1

registry-package@^1.0.0:
  version "1.0.0"
  resolved "https://registry.npmjs.org/registry-package/-/registry-package-1.0.0.tgz"
  integrity sha512-test123

yarn-registry-package@^1.0.0:
  version "1.0.0"
  resolved "https://registry.yarnpkg.com/yarn-registry-package/-/yarn-registry-package-1.0.0.tgz"
  integrity sha512-test456

github-package@https://github.com/user/github-package/archive/v1.0.0.tar.gz:
  version "1.0.0"
  resolved "https://github.com/user/github-package/archive/v1.0.0.tar.gz"
`;
    await fs.writeFile(
      path.join(testRepoPath, 'yarn.lock'),
      lockfileContent
    );

    // Parse lockfile
    const transitiveDeps = await lockfileParser.parseLockfile(testRepoPath);

    // Verify only non-registry URLs were extracted
    assert.strictEqual(transitiveDeps.length, 1, 'Should find only 1 non-registry URL');
    assert.strictEqual(transitiveDeps[0].name, 'github-package', 'Should extract github-package');

    logger.info('✓ npm registry URLs filtered correctly');
  });

  /**
   * Test 7: Handle various URL protocols in yarn lockfile
   * Validates: Requirements 1.1
   */
  it('should extract dependencies with various URL protocols', async () => {
    // Create lockfile with different URL protocols
    const lockfileContent = `# yarn lockfile v1

https-package@https://example.com/package.tar.gz:
  version "1.0.0"
  resolved "https://example.com/package.tar.gz"

http-package@http://example.com/package.tar.gz:
  version "1.0.0"
  resolved "http://example.com/package.tar.gz"

git-package@git://github.com/user/package.git:
  version "1.0.0"
  resolved "git://github.com/user/package.git"

git-https-package@git+https://github.com/user/package.git:
  version "1.0.0"
  resolved "git+https://github.com/user/package.git"

git-http-package@git+http://github.com/user/package.git:
  version "1.0.0"
  resolved "git+http://github.com/user/package.git"
`;
    await fs.writeFile(
      path.join(testRepoPath, 'yarn.lock'),
      lockfileContent
    );

    // Parse lockfile
    const transitiveDeps = await lockfileParser.parseLockfile(testRepoPath);

    // Verify all URL protocols were recognized
    assert.strictEqual(transitiveDeps.length, 5, 'Should find all 5 URL-based dependencies');
    
    const protocols = transitiveDeps.map(dep => {
      if (dep.resolvedUrl.startsWith('https://')) {
        return 'https';
      }
      if (dep.resolvedUrl.startsWith('http://')) {
        return 'http';
      }
      if (dep.resolvedUrl.startsWith('git+https://')) {
        return 'git+https';
      }
      if (dep.resolvedUrl.startsWith('git+http://')) {
        return 'git+http';
      }
      if (dep.resolvedUrl.startsWith('git://')) {
        return 'git';
      }
      return 'unknown';
    }).sort();

    assert.deepStrictEqual(
      protocols,
      ['git', 'git+http', 'git+https', 'http', 'https'],
      'Should recognize all URL protocols'
    );

    logger.info('✓ Various URL protocols handled correctly');
  });

  /**
   * Test 8: Handle empty yarn lockfile
   * Validates: Requirements 1.1
   */
  it('should handle empty yarn lockfile gracefully', async () => {
    // Create minimal empty lockfile
    const lockfileContent = `# yarn lockfile v1
`;
    await fs.writeFile(
      path.join(testRepoPath, 'yarn.lock'),
      lockfileContent
    );

    // Parse lockfile
    const transitiveDeps = await lockfileParser.parseLockfile(testRepoPath);

    // Should return empty array for lockfile with no dependencies
    assert.strictEqual(transitiveDeps.length, 0, 'Should return empty array for empty lockfile');

    logger.info('✓ Empty lockfile handled gracefully');
  });

  /**
   * Test 9: Handle yarn lockfile with only registry dependencies
   * Validates: Requirements 1.1
   */
  it('should return empty array when yarn lockfile contains only registry dependencies', async () => {
    // Create lockfile with only npm registry dependencies
    const lockfileContent = `# yarn lockfile v1

express@^4.18.0:
  version "4.18.0"
  resolved "https://registry.npmjs.org/express/-/express-4.18.0.tgz"
  integrity sha512-test123

lodash@^4.17.21:
  version "4.17.21"
  resolved "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz"
  integrity sha512-test456
`;
    await fs.writeFile(
      path.join(testRepoPath, 'yarn.lock'),
      lockfileContent
    );

    // Parse lockfile
    const transitiveDeps = await lockfileParser.parseLockfile(testRepoPath);

    // Should return empty array since all dependencies are from npm registry
    assert.strictEqual(transitiveDeps.length, 0, 'Should return empty array when all deps are from registry');

    logger.info('✓ Registry-only lockfile handled correctly');
  });

  /**
   * Test 10: Handle yarn lockfile with quoted package names
   * Validates: Requirements 1.1
   */
  it('should handle yarn lockfile with quoted package names', async () => {
    // Create lockfile with quoted package names (common in yarn)
    const lockfileContent = `# yarn lockfile v1

"package-with-quotes@https://github.com/user/package/archive/v1.0.0.tar.gz":
  version "1.0.0"
  resolved "https://github.com/user/package/archive/v1.0.0.tar.gz"

package-without-quotes@https://github.com/user/package2/archive/v2.0.0.tar.gz:
  version "2.0.0"
  resolved "https://github.com/user/package2/archive/v2.0.0.tar.gz"
`;
    await fs.writeFile(
      path.join(testRepoPath, 'yarn.lock'),
      lockfileContent
    );

    // Parse lockfile
    const transitiveDeps = await lockfileParser.parseLockfile(testRepoPath);

    // Verify both quoted and unquoted packages were extracted
    assert.strictEqual(transitiveDeps.length, 2, 'Should find 2 packages');
    
    const quotedPackage = transitiveDeps.find(dep => dep.name === 'package-with-quotes');
    const unquotedPackage = transitiveDeps.find(dep => dep.name === 'package-without-quotes');
    
    assert.ok(quotedPackage, 'Should find quoted package');
    assert.ok(unquotedPackage, 'Should find unquoted package');

    logger.info('✓ Quoted package names handled correctly');
  });

  /**
   * Test 11: Handle yarn lockfile with version ranges
   * Validates: Requirements 1.1
   */
  it('should extract packages with version ranges in declaration', async () => {
    // Create lockfile with version ranges
    const lockfileContent = `# yarn lockfile v1

package-a@^1.0.0, package-a@https://github.com/user/package-a/archive/v1.0.0.tar.gz:
  version "1.0.0"
  resolved "https://github.com/user/package-a/archive/v1.0.0.tar.gz"

package-b@~2.0.0:
  version "2.0.0"
  resolved "https://github.com/user/package-b/archive/v2.0.0.tar.gz"
`;
    await fs.writeFile(
      path.join(testRepoPath, 'yarn.lock'),
      lockfileContent
    );

    // Parse lockfile
    const transitiveDeps = await lockfileParser.parseLockfile(testRepoPath);

    // Verify packages were extracted
    assert.ok(transitiveDeps.length >= 1, 'Should find at least 1 URL-based dependency');
    
    const packageB = transitiveDeps.find(dep => dep.name === 'package-b');
    assert.ok(packageB, 'Should find package-b');

    logger.info('✓ Version ranges handled correctly');
  });

  /**
   * Test 12: Handle yarn lockfile with dependencies field
   * Validates: Requirements 1.1
   */
  it('should parse yarn lockfile with dependencies field', async () => {
    // Create lockfile with dependencies
    const lockfileContent = `# yarn lockfile v1

parent-package@^1.0.0:
  version "1.0.0"
  resolved "https://registry.npmjs.org/parent-package/-/parent-package-1.0.0.tgz"
  dependencies:
    child-package "https://github.com/user/child-package/archive/v1.0.0.tar.gz"

child-package@https://github.com/user/child-package/archive/v1.0.0.tar.gz:
  version "1.0.0"
  resolved "https://github.com/user/child-package/archive/v1.0.0.tar.gz"
`;
    await fs.writeFile(
      path.join(testRepoPath, 'yarn.lock'),
      lockfileContent
    );

    // Parse lockfile
    const transitiveDeps = await lockfileParser.parseLockfile(testRepoPath);

    // Verify child dependency was extracted
    assert.ok(transitiveDeps.length >= 1, 'Should find at least 1 URL-based dependency');
    
    const childDep = transitiveDeps.find(dep => dep.name === 'child-package');
    assert.ok(childDep, 'Should find child-package');

    logger.info('✓ Dependencies field handled correctly');
  });

  /**
   * Test 13: Handle yarn lockfile with integrity hashes
   * Validates: Requirements 1.1
   */
  it('should parse yarn lockfile with integrity hashes', async () => {
    // Create lockfile with integrity hashes
    const lockfileContent = `# yarn lockfile v1

test-package@https://github.com/user/test-package/archive/v1.0.0.tar.gz:
  version "1.0.0"
  resolved "https://github.com/user/test-package/archive/v1.0.0.tar.gz#abc123"
  integrity sha512-abcdef123456
`;
    await fs.writeFile(
      path.join(testRepoPath, 'yarn.lock'),
      lockfileContent
    );

    // Parse lockfile
    const transitiveDeps = await lockfileParser.parseLockfile(testRepoPath);

    // Verify package was extracted with full URL including hash
    assert.strictEqual(transitiveDeps.length, 1, 'Should find 1 URL-based dependency');
    assert.strictEqual(transitiveDeps[0].name, 'test-package', 'Should extract test-package');
    assert.ok(
      transitiveDeps[0].resolvedUrl.includes('#abc123'),
      'Should preserve URL hash'
    );

    logger.info('✓ Integrity hashes handled correctly');
  });
});
